name: Deploy Last_Trade React App to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create .env.production
        run: echo "VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }}" > .env.production

      - name: Verify .env.production
        run: |
          echo "Generated .env.production:"
          cat .env.production

      - name: Build React app
        run: |
          npm run build -- --force
          # Verify the built files contain the new URL
          grep -r "api.pwps.online" dist/ || echo "Warning: New backend URL not found in build"

      - name: Verify Build Output
        run: |
          echo "Checking for backend URL in built files:"
          grep -r "api.pwps.online" dist/ || echo "Backend URL not found (check secrets or build)"

      - name: Debug Backend URL Usage
        run: |
          echo "Checking where the backend URL is used:"
          find dist/ -type f -exec grep -l "https://" {} \; || echo "No files using the backend URL found"

      - name: Copy .htaccess to build output
        run: cp .htaccess dist/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 46.28.45.160
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ./files/public_html/
          dangerous-clean-slate: true