name: Deploy Last_Trade React App to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents before install
        run: ls -la

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: List directory contents after install
        run: ls -la

      - name: Build React app
        run: CI='' npm run build

      - name: List directory contents after build
        run: ls -la build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp://46.28.45.160
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: public_html/