name: Deploy Last_Trade React App to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create .env.production
        run: echo "VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }}" > .env.production

      - name: Clean before build
        run: |
          rm -rf node_modules/.vite
          rm -rf dist

      - name: Build React app
        run: npm run build

      - name: Copy .htaccess to build output
        run: cp .htaccess dist/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 46.28.45.160
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ./
          dangerous-clean-slate: true